# Generated by Django 3.0.2 on 2020-01-22 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oglas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('ime', models.CharField(default=None, max_length=64)),
                ('brojPregleda', models.IntegerField(default=0)),
                ('kategorija', models.CharField(default='opste', max_length=64, null=True)),
                ('datumPostavljanja', models.DateTimeField(auto_now_add=True, null=True)),
                ('prodavac', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Licitacija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vremeLicitacije', models.DateTimeField(auto_now_add=True, null=True)),
                ('cena', models.IntegerField(default=None)),
                ('licitacionar', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
