# Generated by Django 3.0.2 on 2020-01-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oglas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oglas',
            name='preostaloVreme',
            field=models.IntegerField(null=True),
        ),
    ]
