# Generated by Django 3.0.2 on 2020-01-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oglas', '0003_auto_20200124_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='oglas',
            name='opis',
            field=models.CharField(default='Klasican opis', max_length=254, null=True),
        ),
    ]
