# Generated by Django 3.0.2 on 2020-01-27 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oglas', '0006_auto_20200127_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacija',
            name='oglasid',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='oglas.Oglas'),
        ),
    ]
