# Generated by Django 3.0.2 on 2020-01-27 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oglas', '0007_licitacija_oglasid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licitacija',
            old_name='oglasid',
            new_name='oglas',
        ),
    ]
