# Generated by Django 3.0.2 on 2020-01-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oglas', '0008_auto_20200127_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oglas',
            name='cena',
            field=models.IntegerField(default=1),
        ),
    ]
