# Generated by Django 3.0.2 on 2020-01-29 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('korisnik', '0001_initial'),
        ('oglas', '0009_auto_20200128_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licitacija',
            name='licitacionar',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='korisnik.Korisnik'),
        ),
        migrations.AlterField(
            model_name='oglas',
            name='prodavac',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='korisnik.Korisnik'),
        ),
    ]
