# Generated by Django 3.0.2 on 2020-01-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(default=None, max_length=64)),
                ('prezime', models.CharField(default=None, max_length=64)),
                ('email', models.EmailField(default=None, max_length=64)),
                ('adresa', models.CharField(default=None, max_length=64)),
                ('grad', models.CharField(default=None, max_length=64)),
                ('username', models.CharField(default=None, max_length=64)),
                ('password', models.CharField(default=None, max_length=255)),
            ],
        ),
    ]
