# Generated by Django 3.0.2 on 2020-01-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brojevi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brojevi',
            name='drugoPolje',
            field=models.CharField(choices=[('cena', 'Cena oglasa'), ('brojPregleda', 'Broj pregleda'), ('brojLicitacija', 'Broj licitacija po oglasu'), ('brojLicitacijaKorisnik', 'Broj licitacija po korisniku'), ('brojOglasaKorisnik', 'Broj oglasa po korisniku')], default='cena', max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='brojevi',
            name='prvoPolje',
            field=models.CharField(choices=[('cena', 'Cena oglasa'), ('brojPregleda', 'Broj pregleda'), ('brojLicitacija', 'Broj licitacija po oglasu'), ('brojLicitacijaKorisnik', 'Broj licitacija po korisniku'), ('brojOglasaKorisnik', 'Broj oglasa po korisniku')], default='brojPregleda', max_length=22, null=True),
        ),
    ]
